# (!) DO NOT TOUCH (!)
version: 1.0

words: # List of words to scramble
  - ethereal
  - odyssey
  - fortnite
  - fullboxed
  - twohundred
  - reincarnation
  - herobrine

settings:
  # Time to wait between each round
  interval: 60 # Time in seconds

  # How long each game should last before there is a winner
  duration: 30

  # Sound to play when a round starts
  sound: 'random.totem'

  # Min amount of money to win
  min: 1000

  # Max amount of money to win
  max: 100000